name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: juanmiguelruiz/.github/.github/workflows/release-please.yml@main
    secrets:
      APP_ID: ${{ secrets.JMRP_BOT_ID }}
      APP_PRIVATE_KEY: ${{ secrets.JMRP_BOT_PRIVATE_KEY }}
