name: Release Please & Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: juanmiguelruiz/.github/.github/workflows/release-please.yml@main
    secrets:
      APP_ID: ${{ secrets.JMRP_BOT_ID }}
      APP_PRIVATE_KEY: ${{ secrets.JMRP_BOT_PRIVATE_KEY }}y va
  publish-npm:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    uses: juanmiguelruiz/.github/.github/workflows/publish-npm.yml@main
    with:
      node-version: "24.16.0"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
