name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  Call-Release-Please:
    uses: juanmiguelruiz/.github/.github/workflows/release-please.yml@main
    with:
      repository: ${{ github.repository }}
    secrets:
      TOKEN: ${{ secrets.RELEASE_PLEASE_PAT }}
